package enums;

public enum StatusEnum {
    LOG_IN_SUCCESSFULLY,
    LOG_IN_UNSUCCESSFULLY,
    LOG_IN_DENIED,
    UPDATE_SUCCESSFULLY,
    DELETE_SUCCESSFULLY,
    THERE_IS_NO_ANY_PERSON_WITH_THIS_NAME,
    THERE_IS_NO_ANY_PERSON_WITH_THIS_ID,
    INVALID_OPTION,
    PASSWORD_IS_NOT_CORRECT,
    LIST_IS_EMPTY,
    THERE_ARE_MANY_STUDENT_WITH_THIS_NAME,
    THERE_ARE_MANY_TEACHER_WITH_THIS_NAME,

}
